title: Web3 Guide
description: Your Complete Guide to Decentralized Web
baseurl: ""
url: "https://howtoweb3.pro"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Categories
category_list:
  - how-to-guides
  - wallets
  - dapps
  - nfts
  - layer2
  - defi
  - security
  - glossary
